# Generated by Django 4.2.4 on 2023-10-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_categories_slug_alter_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(),
        ),
    ]
