# Generated by Django 4.2.4 on 2023-10-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
