# Generated by Django 4.2.4 on 2024-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courses_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ManyToManyField(to='courses.categories'),
        ),
    ]
