# Generated by Django 4.2.4 on 2024-02-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_courses_category_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='imgURL',
            field=models.FileField(upload_to='images/'),
        ),
    ]
